In [ ]:
#Numpy 
1. What? Library 
2. Where? Data Analytics 
3. What is its feature? Data Structure - n - Dimensional array.
 And perform Matrix and Mathematical Ops easily 

In [2]:
#3 Reasons Why numpy?
#1. Memory Usage! 
import numpy as np #call Numpy I will use np instaead of Numpy as such
import sys

#creating a numpy array 
array_numpy = np.arange(100)
print("Size of Numpy array",array_numpy.size * array_numpy.itemsize)

Size of Numpy array 800


In [2]:
list_range = range(0,100)
print("Size of the list:",sys.getsizeof(1)*len(list_range))

Size of the list: 2800


In [3]:
#Convienient
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1+a2)

[5 7 9]


In [4]:
#1. Memory Efficient 
#2. Convienient
#3. Faster

In [4]:
'''
Install 
pip - Package installer for python
!pip install numpy 
!conda install numpy --y
!pip3 install numpy

'''

In [7]:
import numpy as n
arr = n.array([1,2,3,5])

In [9]:
import numpy as np
arr = np.array([1,2,3,4,56])

In [10]:
print(type(arr))
#ndarray = 'n' Dimensional Array

<class 'numpy.ndarray'>


In [11]:
type(arr[0])

numpy.int64

In [12]:
#Homogenous - all of it will be same datatypes

In [16]:
arr = np.array([1,2,3,4,'Inceptez'])
print(type(arr[0]))

<class 'numpy.str_'>


In [15]:
print(np.__version__)

1.19.5


In [40]:
arr_2d = np.array([[1,2,3,4,5],[2,3,0,4,7]]) 

#warning VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
 # """Entry point for launching an IPython kernel.

In [41]:
arr_2d.shape

(2, 5)

In [42]:
arr_2d

array([[1, 2, 3, 4, 5],
       [2, 3, 0, 4, 7]])

In [ ]:
#Functions involved in Creating an Array!

In [52]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

In [53]:
a.reshape((4,4))
#ValueError: cannot reshape array of size 15 into shape (4,4) 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [76]:
#Linspace: This function create elements which are equally 
#spaced from each other
#(start, stop, Count of elements it has to generate from Starting and END inc.)
np.linspace(0,100,10,endpoint=False)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [75]:
#Arange
#Generates values based on the step you specify! 
np.arange(0,100,10)

In [61]:
#square matrix The number of rows = Number of Columns (Square matrix) multiplical 1*3
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
#zero - Fills the shape specified in the parameter with zeros 
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [64]:
#zero - Fills the shape specified in the parameter with zeros 
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
a = np.diag([1,2,3,4,5])

In [66]:
#square matrix The number of rows = Number of Columns (Square matrix) multiplical 1*3
np.eye((3))[::-1]

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [73]:
#zero - Fills the shape specified in the parameter with zeros 
np.zeros?

In [74]:
np.eye?

In [79]:
#operations with Numpy array 
arr = np.array([20,30,40])
dup = arr.copy()
arr[0] = 60
print(arr)
print(dup)

[60 30 40]
[20 30 40]


In [80]:
#operations with Numpy array 
arr = np.array([20,30,40])
dup = arr.view()
arr[0] = 60
print(arr)
print(dup)

[60 30 40]
[60 30 40]


In [81]:
#Iterations Throught the array
#For loops - 'n' of these arrays

In [82]:
for i in arr: 
  print(i)

60
30
40


In [85]:
for i in arr_2d:
  for x in i:
    print(x)

1
2
3
4
5
2
3
0
4
7


In [ ]:
arr_2d = np.array([[1,2,3,4,5],[2,3,0,4,7]]) 

In [25]:
arr_3d = np.array([
                   [[1,6,8],[6,7,8],[10,21,24],[23,25,26]],
                   [[2,6,8],[2,7,8],[2,21,24],[2,25,26]],
                   [[2,6,8],[2,7,8],[2,21,24],[2,25,26]]
                  ])

In [26]:
arr_3d.shape

(3, 4, 3)

In [8]:
for room in arr_3d:
  print("Inside the Room",room)
  for each_row in room:
    print("Inside room1: {} row".format(each_row))
    for data_scientist in each_row:
      print(data_scientist)

Inside the Room [[ 1  6  8]
 [ 6  7  8]
 [10 21 24]
 [23 25 26]]
Inside room1: [1 6 8] row
1
6
8
Inside room1: [6 7 8] row
6
7
8
Inside room1: [10 21 24] row
10
21
24
Inside room1: [23 25 26] row
23
25
26


In [27]:
## Addition, Subtraction and Multiplication in numpy array
arr1 = np.array(range(1,17,1))
arr1 = arr1.reshape(4,4)

In [28]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [30]:
## Addition, Subtraction and Multiplication in numpy array
arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(4,4)

In [31]:
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [32]:
arr1+arr2

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132],
       [143, 154, 165, 176]])

In [38]:
np.add(arr1,arr2)

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132],
       [143, 154, 165, 176]])

In [35]:
a = np.array([1,2,3,4])
b = np.array([1,2])
a+b

ValueError: ignored

In [43]:
arr3 = arr2-arr1

In [39]:
#subtraction - Numbers taken in same order
#differece - Biggest number - Smallest number
np.subtract(arr1,arr2)

array([[  -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72],
       [ -81,  -90,  -99, -108],
       [-117, -126, -135, -144]])

In [42]:
arr1 = np.array(range(1,17,1))
arr1 = arr1.reshape(4,4)
arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(4,4)
arr1+arr2

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132],
       [143, 154, 165, 176]])

In [44]:
arr3

array([[  9,  18,  27,  36],
       [ 45,  54,  63,  72],
       [ 81,  90,  99, 108],
       [117, 126, 135, 144]])

In [45]:
np.add(arr1,arr2)

(array([2, 3, 3, 3, 3]), array([3, 0, 1, 2, 3]))

In [47]:
np.multiply?
#Multiply arguments element-wise.

In [48]:
#Matrix multiplication 
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [52]:
arr1 = np.array([[2,3,6],[4,5,7]])
arr2 = np.array([[2,5,6],[7,8,7],[9,10,8]])
np.dot(arr1,arr2)

array([[ 79,  94,  81],
       [106, 130, 115]])

In [53]:
## Join numpy arrays
arr1  = np.array([2,3,6])
arr2 = np.array([5,6,7])

In [63]:
np.stack((arr1,arr2),axis = 0)

array([[2, 3, 6],
       [5, 6, 7]])

In [64]:
arr3

array([[2, 5],
       [3, 6],
       [6, 7]])

In [65]:
res = []
k = 1
for sub in arr3:
  res.append(sub[k])

In [66]:
res

[5, 6, 7]

In [58]:
arr3 = np.stack((arr1,arr2),axis = 1)

In [67]:
#Transpose of any matrix
arr arr3.T

array([[2, 3, 6],
       [5, 6, 7]])

In [68]:
## Join numpy arrays
arr1  = np.array([26,30,6])
arr2 = np.array([25,6,7])
arr3 = np.stack((arr1,arr2),axis = 0)

In [69]:
arr3

array([[26, 30,  6],
       [25,  6,  7]])

In [70]:
np.sort(arr3)

array([[ 6, 26, 30],
       [ 6,  7, 25]])

In [ ]:
A.I = I.A = A (for any square)

In [71]:
np.absolute(np.subtract(arr1,arr2))

array([ 1, 24,  1])